{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "Cloud Foundry API",
    "description" : "API compatible with Cloud Controller API v3, enabling developers to interact with Cloud Foundry resources programmatically.\n",
    "termsOfService" : "https://cloudfoundry.org/terms",
    "contact" : {
      "name" : "Cloud Foundry Foundation",
      "url" : "https://cloudfoundry.org"
    },
    "license" : {
      "name" : "Apache 2.0",
      "url" : "https://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version" : "0.0.1"
  },
  "servers" : [ {
    "url" : "https://api.example.com",
    "description" : "Production server (default)"
  }, {
    "url" : "https://staging-api.example.com",
    "description" : "Staging server for testing"
  }, {
    "url" : "http://localhost:8080",
    "description" : "Local development server"
  }, {
    "url" : "{api_base_url}",
    "description" : "API Base URL (replace {api_base_url} with the appropriate base URL)"
  } ],
  "paths" : {
    "/v3/info" : {
      "summary" : "Retrieve platform information",
      "description" : "Returns metadata about the platform, such as the supported API versions, feature flags, and other relevant information.\n"
    },
    "/v3/apps" : {
      "summary" : "Manage applications.",
      "description" : "Interact with application resources."
    },
    "/v3/apps/{guid}" : {
      "summary" : "Manage a specific application.",
      "description" : "Access, update, or delete a specific application by GUID."
    },
    "/v3/apps/{guid}/processes" : {
      "summary" : "List processes for an application.",
      "description" : "Retrieve processes associated with the specified application."
    },
    "/v3/apps/{guid}/tasks" : {
      "summary" : "List tasks for an application.",
      "description" : "Retrieve tasks associated with the specified application."
    },
    "/v3/buildpacks" : {
      "summary" : "Manage buildpacks.",
      "description" : "List or update buildpacks used for building applications."
    },
    "/v3/buildpacks/{guid}" : {
      "summary" : "Manage a specific buildpack.",
      "description" : "Access or update a specific buildpack by GUID."
    },
    "/v3/builds" : {
      "summary" : "Manage builds.",
      "description" : "List or create builds for applications."
    },
    "/v3/builds/{guid}" : {
      "summary" : "Manage a specific build.",
      "description" : "Access details of a specific build by GUID."
    },
    "/v3/droplets" : {
      "summary" : "Manage droplets.",
      "description" : "Interact with droplets, which are deployable artifacts of builds."
    },
    "/v3/droplets/{guid}" : {
      "summary" : "Manage a specific droplet.",
      "description" : "Access or update a specific droplet by GUID."
    },
    "/v3/droplets/{guid}/assignments" : {
      "summary" : "Assign droplets to applications.",
      "description" : "Assign a specific droplet to an application by GUID."
    },
    "/v3/environment_variables" : {
      "summary" : "Manage environment variables.",
      "description" : "Manage environment variables at the platform level."
    },
    "/v3/events" : {
      "summary" : "List audit events.",
      "description" : "Access audit events generated by API operations."
    },
    "/v3/features" : {
      "summary" : "Manage platform-wide features.",
      "description" : "List or update features available in the platform."
    },
    "/v3/features/{name}" : {
      "summary" : "Manage a specific platform feature.",
      "description" : "Access or update details of a specific platform feature by name."
    },
    "/v3/jobs" : {
      "summary" : "Manage jobs for long-running tasks.",
      "description" : "List or monitor the status of background jobs."
    },
    "/v3/jobs/{guid}" : {
      "summary" : "Monitor the status of a specific job.",
      "description" : "Check the status or result of a background job by GUID."
    },
    "/v3/organizations" : {
      "summary" : "Manage organizations.",
      "description" : "List or manage organizations in the platform."
    },
    "/v3/organizations/{guid}" : {
      "summary" : "Manage a specific organization.",
      "description" : "Access or update details of an organization by GUID."
    },
    "/v3/organizations/{guid}/spaces" : {
      "summary" : "List spaces in an organization.",
      "description" : "Retrieve all spaces associated with the specified organization."
    },
    "/v3/packages" : {
      "summary" : "Manage packages.",
      "description" : "List, create, or update packages for applications."
    },
    "/v3/packages/{guid}" : {
      "summary" : "Manage a specific package.",
      "description" : "Access or update details of a package by GUID."
    },
    "/v3/processes" : {
      "summary" : "Manage processes.",
      "description" : "List or update processes for applications."
    },
    "/v3/processes/{guid}" : {
      "summary" : "Manage a specific process.",
      "description" : "Access or update details of a specific process by GUID."
    },
    "/v3/processes/{guid}/instances" : {
      "summary" : "Scale or restart instances of a process.",
      "description" : "Manage instances associated with a specific process."
    },
    "/v3/roles" : {
      "summary" : "Manage user roles and permissions.",
      "description" : "List or update roles for users in organizations or spaces."
    },
    "/v3/routes" : {
      "summary" : "Manage routes.",
      "description" : "List or create routes for applications."
    },
    "/v3/routes/{guid}" : {
      "summary" : "Manage a specific route.",
      "description" : "Access or update details of a route by GUID."
    },
    "/v3/service_brokers" : {
      "summary" : "Manage service brokers.",
      "description" : "List or manage service brokers in the platform."
    },
    "/v3/service_instances" : {
      "summary" : "Manage service instances.",
      "description" : "Create, update, or delete service instances."
    },
    "/v3/service_bindings" : {
      "summary" : "Manage service bindings.",
      "description" : "Manage bindings between service instances and applications."
    },
    "/v3/spaces" : {
      "summary" : "Manage spaces.",
      "description" : "List, create, or update spaces in the platform."
    },
    "/v3/spaces/{guid}" : {
      "summary" : "Manage a specific space.",
      "description" : "Access or update details of a specific space by GUID."
    },
    "/v3/tasks" : {
      "summary" : "Manage tasks.",
      "description" : "List, create, or update tasks for applications."
    },
    "/v3/tasks/{guid}" : {
      "summary" : "Manage a specific task.",
      "description" : "Access or update details of a specific task by GUID."
    },
    "/v3/users" : {
      "summary" : "Manage users.",
      "description" : "List or manage user accounts in the platform."
    },
    "/v3/users/{guid}" : {
      "summary" : "Manage a specific user.",
      "description" : "Access or update details of a specific user by GUID."
    }
  },
  "components" : { }
}