type: object
allOf:
  - $ref: ./baseSchema.yaml
  - properties:
      name:
        type: string
        description: The name of the stack.
      description:
        type: string
        description: A description of the stack.
      build_rootfs_image:
        type: string
        description: >-
          The name of the stack image associated with staging/building Apps. If
          a stack does not have unique images, this will be the same as the
          stack name.
      run_rootfs_image:
        type: string
        description: >-
          The name of the stack image associated with running Apps. If a stack
          does not have unique images, this will be the same as the stack name.
      default:
        type: boolean
        description: Whether the stack is the default stack
      metadata:
        $ref: ./metadata.yaml
      links:
        type: object
        properties:
          self:
            $ref: ./link.yaml
description: A stack is a pre-built root filesystem that can be used to run applications.
