openapi: 3.1.0
info:
  title: Cloud Foundry V3 API
  description: >-
    # Welcome to the Cloud Foundry V3 API docs! Version 3 adds support for
    several key features:


    - Running one-off tasks on Cloud Foundry

    - Applications consisting of several processes via a Procfile

    - Direct access to application packages and droplets

    - Changing application source code without stopping the app via deployments


    # Getting help

    The CAPI team can most easily be reached on our Slack channel for questions
    and issues regarding the API. To report an issue with the docs or API,
    please feel free to file a GitHub issue on our API repo,
    cloud_controller_ng.

    We recommend reaching out to Slack first as we will be most responsive
    there.
        
    # More resources

    - The Cloud Foundry V2 API is still depricated but still available for
    interacting with Cloud Foundry.

    - Running Tasks

    - V3 API Documentation OpenAPI Spec Source Code.
  version: 3.x.0  
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    email: cf-dev@lists.cloudfoundry.org
    name: Cloud Foundry CAPI Team
    url: https://cloudfoundry.slack.com/archives/C07C04W4Q
servers:
  - url: http://127.0.0.1:4010
    description: Prism mock server
components:
  securitySchemes:
    oauth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://uaa.cloudfoundry.local/api-oauth/dialog
          scopes:
            cloud_controller.admin: This scope provides read and write access to all resources
            cloud_controller.admin_read_only: This scope provides read only access to all resources
            cloud_controller.global_auditor: This scope provides read access to all resources
            cloud_controller.read: Read access to the Cloud Controller
            cloud_controller.write: Write access to the Cloud Controller
            cloud_controller.update_build_state: >-
              This scope allows its bearer to update the state of a build;
              currently only used when updating builds
            cloud_controller_service_permissions.read: >-
              This scope provides read only access for service instance
              permissions
    bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Bearer JWT token authentication
paths:
  /:
    $ref: paths/root.yaml
