get:
  tags:
    - Revisions
  summary: Get environment variables for a revision
  description: >-
    Retrieve the environment variables associated with a specific revision of an
    app.
  operationId: getEnvironmentVariablesForRevision
  parameters:
    - $ref: ../components/parameters/guid.yaml
    - name: version
      in: path
      required: true
      schema:
        type: integer
        description: The version number of the revision
  responses:
    '200':
      description: Successfully retrieved environment variables
      content:
        application/json:
          schema:
            type: object
            properties:
              var:
                type: object
                additionalProperties:
                  type: string
                description: Environment variables for the revision
              links:
                type: object
                properties:
                  self:
                    allOf:
                      - $ref: ../components/schemas/link.yaml
                      - description: Link to the current endpoint
                  revision:
                    allOf:
                      - $ref: ../components/schemas/link.yaml
                      - description: Link to the revision
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../components/schemas/errors.yaml
          example:
            errors:
              - code: 100001
                title: CF-AppInvalid
                detail: 'The app is invalid: %s'
    '401':
      $ref: ../components/responses/401Unauthorized.yaml
    '403':
      $ref: ../components/responses/403Forbidden.yaml
    '404':
      description: App or revision not found
      content:
        application/json:
          schema:
            $ref: ../components/schemas/errors.yaml
          example:
            errors:
              - code: 100004
                title: CF-AppNotFound
                detail: 'The app could not be found: %s'
  security:
    - oauth:
        - cloud_controller.read
