get:
  summary: Get environment variables for an app
  description: >-
    Retrieve the environment variables that are associated with the given app.
    For the entire list of environment variables that will be available to the
    app at runtime, see the env endpoint.
  operationId: getEnvironmentVariablesForApp
  tags:
    - Apps
  parameters:
    - $ref: ../components/parameters/Guid.yaml
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/AppEnvironmentVariables.yaml
    '400':
      $ref: ../components/responses/400.yaml
    '401':
      $ref: ../components/responses/401.yaml
    '403':
      $ref: ../components/responses/403.yaml
    '404':
      $ref: ../components/responses/404.yaml
    '429':
      $ref: ../components/responses/429.yaml
    '500':
      $ref: ../components/responses/500.yaml
patch:
  summary: Update environment variables for an app
  description: >-
    Update the environment variables associated with the given app. The
    variables given in the request will be merged with the existing app
    environment variables. Any requested variables with a value of `null` will
    be removed from the app. Environment variable names may not start with
    VCAP_. PORT is not a valid environment variable. The updated environment
    variables will not take effect until the app is restarted.
  operationId: updateEnvironmentVariablesForApp
  tags:
    - Apps
  parameters:
    - $ref: ../components/parameters/Guid.yaml
  requestBody:
    content:
      application/json:
        schema:
          type: object
          properties:
            var:
              type: object
              additionalProperties:
                type: string
                maxLength: 8192
              description: Environment variables to inject; keys and values must be strings
              propertyNames:
                type: string
                pattern: ^[A-Za-z_][A-Za-z0-9_]*$
              maxProperties: 512
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/AppEnvironmentVariables.yaml
    '401':
      $ref: ../components/responses/401.yaml
    '403':
      $ref: ../components/responses/403.yaml
    '404':
      $ref: ../components/responses/404.yaml
    '422':
      $ref: ../components/responses/422.yaml
    '429':
      $ref: ../components/responses/429.yaml
    '500':
      $ref: ../components/responses/500.yaml
