get:
  tags:
    - Deployments
  summary: List deployments
  description: Retrieve a list of all deployments the user has access to.
  operationId: listDeployments
  parameters:
    - $ref: ../components/parameters/page.yaml
    - $ref: ../components/parameters/perPage.yaml
    - $ref: ../components/parameters/orderBy.yaml
    - $ref: ../components/parameters/createdAts.yaml
    - $ref: ../components/parameters/updatedAts.yaml
    - $ref: ../components/parameters/labelSelector.yaml
    - name: app_guids
      in: query
      schema:
        type: array
        items:
          type: string
      description: Comma-delimited list of app GUIDs to filter by
    - name: states
      in: query
      schema:
        type: array
        items:
          type: string
      description: Comma-delimited list of deployment states to filter by
    - name: status_reasons
      in: query
      schema:
        type: array
        items:
          type: string
      description: >-
        Comma-delimited list of status reasons to filter by; valid values
        include DEPLOYING, PAUSED, CANCELING, DEPLOYED, CANCELED, SUPERSEDED
    - name: status_values
      in: query
      schema:
        type: array
        items:
          type: string
      description: >-
        Comma-delimited list of status values to filter by; valid values include
        ACTIVE and FINALIZED
  responses:
    '200':
      description: List of deployments
      content:
        application/json:
          schema:
            $ref: ../components/schemas/deploymentList.yaml
    '401':
      $ref: ../components/responses/401Unauthorized.yaml
    '403':
      $ref: ../components/responses/403Forbidden.yaml
post:
  tags:
    - Deployments
  summary: Create a deployment
  description: Create a new deployment.
  operationId: createDeployment
  requestBody:
    description: Deployment object that needs to be created
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            relationships:
              $ref: ../components/schemas/relationships.yaml
            strategy:
              type: string
            droplet:
              $ref: ../components/schemas/relationship.yaml
            revision:
              $ref: ../components/schemas/relationship.yaml
            options:
              type: object
              properties:
                max_in_flight:
                  type: integer
                  description: The maximum number of new instances to deploy simultaneously
            metadata:
              $ref: ../components/schemas/metadata.yaml
  responses:
    '201':
      description: Successfully created deployment
      content:
        application/json:
          schema:
            $ref: ../components/schemas/deployment.yaml
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../components/schemas/errors.yaml
          example:
            errors:
              - code: 100001
                title: CF-AppInvalid
                detail: 'The app is invalid: %s'
    '401':
      $ref: ../components/responses/401Unauthorized.yaml
    '403':
      $ref: ../components/responses/403Forbidden.yaml
  security:
    - oauth:
        - cloud_controller.write
