get:
  summary: Get a deployment
  description: Retrieve a deployment.
  operationId: getDeployment
  tags:
    - Deployments
  parameters:
    - $ref: ../components/parameters/Guid.yaml
  responses:
    '200':
      description: Successfully retrieved deployment
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Deployment.yaml
      links:
        app:
          operationId: getApp
          parameters:
            guid: $response.body#/relationships/app/data/guid
          description: Retrieve the app for this deployment
        droplet:
          operationId: getDroplet
          parameters:
            guid: $response.body#/droplet/data/guid
          description: Retrieve the droplet for this deployment
        previous_droplet:
          operationId: getDroplet
          parameters:
            guid: $response.body#/previous_droplet/data/guid
          description: Retrieve the previous droplet for this deployment
    '401':
      $ref: ../components/responses/401.yaml
    '403':
      $ref: ../components/responses/403.yaml
    '404':
      $ref: ../components/responses/404.yaml
    '429':
      $ref: ../components/responses/429.yaml
patch:
  summary: Update a deployment
  description: Update a deployment.
  operationId: updateDeployment
  tags:
    - Deployments
  parameters:
    - $ref: ../components/parameters/Guid.yaml
  requestBody:
    description: Deployment object that needs to be updated
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            metadata:
              $ref: ../components/schemas/Metadata.yaml
          description: Request schema for updating a deployment
  responses:
    '200':
      description: Successfully updated deployment
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Deployment.yaml
    '400':
      $ref: ../components/responses/400.yaml
    '401':
      $ref: ../components/responses/401.yaml
    '403':
      $ref: ../components/responses/403.yaml
    '404':
      $ref: ../components/responses/404.yaml
    '409':
      $ref: ../components/responses/409.yaml
    '422':
      $ref: ../components/responses/422.yaml
    '429':
      $ref: ../components/responses/429.yaml
    '500':
      $ref: ../components/responses/500.yaml
    '503':
      $ref: ../components/responses/503.yaml
