get:
  summary: Get an environment variable group
  description: Retrieve an environment variable group.
  operationId: getEnvironmentVariableGroup
  tags:
    - EnvironmentVariableGroups
  parameters:
    - name: name
      in: path
      required: true
      schema:
        type: string
        enum:
          - running
          - staging
      description: The name of the environment variable group, either running or staging.
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/EnvironmentVariableGroup.yaml
    '400':
      $ref: ../components/responses/400.yaml
    '401':
      $ref: ../components/responses/401.yaml
    '403':
      $ref: ../components/responses/403.yaml
    '404':
      $ref: ../components/responses/404.yaml
    '409':
      $ref: ../components/responses/409.yaml
    '422':
      $ref: ../components/responses/422.yaml
    '429':
      $ref: ../components/responses/429.yaml
    '500':
      $ref: ../components/responses/500.yaml
    '502':
      $ref: ../components/responses/502.yaml
    '503':
      $ref: ../components/responses/503.yaml
patch:
  summary: Update environment variable group
  description: >-
    Update the environment variable group. The variables given in the request
    will be merged with the existing environment variable group. Any requested
    variables with a value of `null` will be removed from the group. Environment
    variable names may not start with VCAP_. PORT is not a valid environment
    variable.


    Variables updated in the **running** environment variable group will not
    take effect until apps are restarted.
  operationId: updateEnvironmentVariableGroup
  tags:
    - EnvironmentVariableGroups
  parameters:
    - name: name
      in: path
      required: true
      schema:
        type: string
        enum:
          - running
          - staging
      description: The name of the environment variable group, either running or staging.
  requestBody:
    description: The environment variables to update
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            var:
              type: object
              additionalProperties:
                type: string
              description: Environment variables to inject; keys and values must be strings
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/EnvironmentVariableGroup.yaml
    '400':
      $ref: ../components/responses/400.yaml
    '401':
      $ref: ../components/responses/401.yaml
    '403':
      $ref: ../components/responses/403.yaml
    '404':
      $ref: ../components/responses/404.yaml
    '409':
      $ref: ../components/responses/409.yaml
    '422':
      $ref: ../components/responses/422.yaml
    '429':
      $ref: ../components/responses/429.yaml
    '500':
      $ref: ../components/responses/500.yaml
    '503':
      $ref: ../components/responses/503.yaml
