get:
  tags:
    - EnvironmentVariableGroups
  summary: Get running environment variable group
  description: Retrieve the environment variable group for running applications.
  operationId: getRunningEnvironmentVariableGroup
  responses:
    '200':
      description: Successfully retrieved running environment variable group
      content:
        application/json:
          schema:
            $ref: ../components/schemas/environmentVariableGroup.yaml
    '401':
      $ref: ../components/responses/401Unauthorized.yaml
    '403':
      $ref: ../components/responses/403Forbidden.yaml
    '500':
      $ref: ../components/responses/500Unauthorized.yaml
  security:
    - oauth:
        - cloud_controller.read
patch:
  tags:
    - EnvironmentVariableGroups
  summary: Update running environment variable group
  description: Update the environment variable group for running applications.
  operationId: updateRunningEnvironmentVariableGroup
  requestBody:
    description: The environment variables to update
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            var:
              type: object
              additionalProperties:
                type: string
              description: Environment variables to inject; keys and values must be strings
  responses:
    '200':
      description: Successfully updated running environment variable group
      content:
        application/json:
          schema:
            $ref: ../components/schemas/environmentVariableGroup.yaml
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../components/schemas/errors.yaml
          example:
            errors:
              - code: 380001
                title: CF-EnvironmentVariableGroupInvalid
                detail: 'The Environment Variable Group is invalid: %s'
    '401':
      $ref: ../components/responses/401Unauthorized.yaml
    '403':
      $ref: ../components/responses/403Forbidden.yaml
    '500':
      $ref: ../components/responses/500Unauthorized.yaml
  security:
    - oauth:
        - cloud_controller.write
