delete:
  tags:
    - Routes
  summary: Delete unmapped routes for a space
  description: Delete routes that are unmapped in a specific space.
  operationId: deleteUnmappedRoutesForSpace
  parameters:
    - $ref: ../components/parameters/guid.yaml
  responses:
    '204':
      description: Successfully deleted unmapped routes from the space
    '401':
      $ref: ../components/responses/401Unauthorized.yaml
    '403':
      $ref: ../components/responses/403Forbidden.yaml
    '404':
      description: Space not found
      content:
        application/json:
          schema:
            $ref: ../components/schemas/errors.yaml
          example:
            errors:
              - code: 40004
                title: CF-SpaceNotFound
                detail: 'The app space could not be found: %s'
  security:
    - oauth:
        - cloud_controller.write
