name: Bundle OpenAPI Spec

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 0 * * *'
  
jobs:
  bundle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install packages
        run: make upgrade-packages-local

      - name: Bundle OpenAPI Spec
        run: make bundle