name: Generate OpenAPI Spec

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Install Spectral CLI
        run: npm install -g @stoplight/spectral-cli

      - name: Install swagger-cli
        run: npm install -g @apidevtools/swagger-cli

      - name: Lint OpenAPI Spec
        run: bash scripts/generate-spec.sh