name: Lint OpenAPI Spec

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install Redocly CLI
        run: npm install -g "@redocly/cli"

      - name: Install Spectral CLI
        run: npm install -g @stoplight/spectral-cli
        
      - name: Lint OpenAPI Spec
        run: bash scripts/lint.sh