name: Validate OpenAPI Spec

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23' # Ensure compatibility with swagger-cli

      - name: Install swagger-cli
        run: npm install -g @apidevtools/swagger-cli

      - name: Run validate script
        run: bash scripts/validate.sh